ENABLE_BLACK_OPENING_SEED = True
ENABLE_WHITE_OPENING_DISRUPTION = False

ENABLE_GENERAL_PLAN_EVAL = False
ENABLE_INITIATIVE_EVAL = False
ENABLE_OPPONENT_PLAN_BLOCKING = False
ENABLE_LEAF_NEXT_THREAT = False
ENABLE_PLAN_CANDIDATES = False

OPENING_STRATEGY_MAX_MOVES = 16
BLACK_OPENING_SEED_WEIGHT = 1.0
WHITE_OPENING_DISRUPTION_WEIGHT = 1.0
BLACK_OPENING_SEED_SCORE_CAP = 800_000

BLACK_OPENING_CENTER_CONNECTION_BONUS = 80_000
BLACK_OPENING_TWO_DIRECTION_BONUS = 120_000
BLACK_OPENING_THREE_DIRECTION_BONUS = 260_000
BLACK_OPENING_OPEN_TWO_MULTI_DIR_BONUS = 180_000
BLACK_OPENING_OPEN_THREE_MULTI_DIR_BONUS = 350_000
BLACK_OPENING_FUTURE_43_MULTI_BONUS = 600_000
